keys:
  - &admin_joris age18nh2kgk00un457cjxgaf0kfq9c6wlw6vmupl3zlvtc3s73v5tcesv35nnu
  - &server_node1 age1gr8v4v3ypjgtg4j0frju0kwx7nka6zs8wmact3pamzqql20y85rslkufrz
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_joris
      - *server_node1
